# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PruebaMarvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PruebaMarvel
  pod 'Kingfisher'
  pod 'MBProgressHUD', '~> 1.2'

end
